"""Single GET route registry; handler implementations live in domain modules."""
from __future__ import annotations
from routes_get_dependencies import unquote
from routes_get_system import *
from routes_get_performance import *
from routes_get_scanner import *
from routes_get_stock import *
from routes_get_research import *
from routes_get_research_attribution import *
from routes_get_help import *
from routes_get_control import *
from routes_get_clean_core import *

# Exact-match routes. Multiple aliases point at the same handler, matching
# the original main.py `if path in (...)` groupings 1:1.
ROUTES = {
    "/api/ready": r_ready,
    "/api/frontend-identity": r_frontend_identity,
    "/api/system-help": r_system_help, "/api/help": r_system_help, "/api/endpoints": r_system_help,
    "/api/architecture": r_architecture,
    "/api/clean-core/status": r_clean_core_status,
    "/api/clean-core/gate1-sample": r_clean_core_gate1_sample,
    "/api/clean-core/browser-proof": r_clean_core_browser_proof,
    "/api/health": r_health,
    "/api/product-readiness": r_product_readiness, "/api/product-state": r_product_state, "/api/status": r_health, "/api/state": r_health,
    "/api/first-useful-mode": r_first_useful_mode_status,
    "/api/market-depth": r_market_depth,
    "/api/system-health": r_system_health, "/api/pipeline-health": r_pipeline_health,
    "/api/runtime-controller": r_runtime_controller,
    "/api/runtime-controller/events": r_runtime_controller_events,
    "/api/runtime-controller/component": r_runtime_controller_component,
    "/api/level5-control-plane": r_level5_control_plane,
    "/api/operations/summary": r_operations_summary,
    "/api/operations/jobs": r_operations_jobs,
    "/api/operations/events": r_operations_events,
    "/api/operations/logs": r_operations_logs,
    "/api/operations/maturity-blockers": r_operations_maturity_blockers,
    "/api/workload-governor": r_workload_governor,
    "/api/real-walk-forward": r_real_walk_forward,
    "/api/strategy-validation": r_strategy_validation,
    "/api/evidence-score-validation": r_evidence_score_validation,
    "/api/delivery-data": r_delivery_data,
    "/api/delivery-sync": r_delivery_sync, "/api/reload-delivery": r_delivery_sync,
    "/api/bulk-deals": r_bulk_deals,
    "/api/market-breadth": r_market_breadth,
    "/api/reference-data-runs": r_reference_data_runs,
    "/api/institutional-flow": r_institutional_flow,
    "/api/analytical-projection/status": r_analytical_projection_status,
    "/api/event-calendar": r_event_calendar,
    "/api/auth-test": r_auth_test,
    "/api/instruments/status": r_instruments_status,
    "/api/scanner-audit": r_scanner_audit,
    "/api/scanner": r_scanner_status, "/api/scanner/status": r_scanner_status, "/api/scanner-status": r_scanner_status, "/api/progress": r_scanner_status,
    "/api/scanner/stage-members": r_scanner_stage_members,
    "/api/dashboard-state": r_dashboard_state, "/api/dashboard": r_dashboard_state,
    "/api/dashboard-cards": r_dashboard_cards,
    "/api/trader-workspace": r_trader_workspace,
    "/api/trader-live-state": r_trader_live_state,
    "/api/trader-research": r_trader_research,
    "/api/today-entries": r_today_entries,
    "/api/model-portfolio": r_model_portfolio,
    "/api/model-lifecycle": r_quant_model_governance,
    "/api/operator-settings": r_operator_settings, "/api/settings": r_operator_settings,
    "/api/quote-delta": r_quote_delta, "/api/live-quotes": r_quote_delta,
    "/api/live-market/status": r_live_market_status,
    "/api/live-market/deltas": r_live_deltas,
    "/api/suggest": r_suggest,
    "/api/daily-performance": r_daily_performance,
    "/api/daily-learning": r_daily_learning,
    "/api/backfill-progress": r_backfill_progress,
    "/api/trade-journal": r_trade_journal,
    "/api/signal-accuracy/export": r_signal_accuracy_export,
    "/api/market/heatmap": r_heatmap, "/api/heatmap": r_heatmap, "/api/index-heatmap": r_heatmap,
    "/api/trade-journal/summary": r_journal_summary, "/api/journal/summary": r_journal_summary,
    "/api/day-performance/summary": r_journal_summary, "/api/performance/summary": r_journal_summary,
    "/api/performance": r_journal_summary,
    "/api/indices": r_indices, "/api/index-context": r_indices, "/api/market": r_indices,
    "/api/market/status": r_market_status,
    "/api/data-coverage": r_data_coverage, "/api/historical-coverage": r_data_coverage,
    "/api/priority-pipeline": r_priority_pipeline,
    "/api/priority-pipeline/recovery": r_priority_pipeline_recovery,
    "/api/evidence-snapshot": r_evidence_snapshot,
    "/api/cross-plane-reconciliation": r_cross_plane_reconciliation,
    "/api/level5-evidence-matrix": r_level5_evidence_matrix,
    "/api/level5-operational-proof": r_level5_operational_proof,
    "/api/ml-population-qualification": r_ml_population_qualification,
    "/api/historical": r_historical, "/api/candles": r_historical,
    "/api/analyze": r_analyze,
    "/api/market-intelligence": r_market_intelligence,
    "/api/stock-snapshot": r_stock_snapshot,
    "/api/chart-data": r_chart_data,
    "/api/live-chart-bar": r_live_chart_bar,
    "/api/stock-intelligence": r_stock_intelligence,
    "/api/market-radar": r_market_radar,
    "/api/learning-health": r_learning_health, "/api/winrate-diagnostics": r_winrate_diagnostics,
    "/api/mtf-trend": r_mtf_trend,
    "/api/decision-ledger": r_decision_ledger,
    "/api/canonical-decision": r_canonical_decision,
    "/api/historical-readiness": r_historical_readiness,
    "/api/research-libraries": r_research_libraries,
    "/api/research-lifecycle-reconciliation": r_research_lifecycle_reconciliation,
    "/api/decision-lifecycle": r_decision_lifecycle,
    "/api/research-retention": r_research_retention,
    "/api/research-preservation-manifest": r_research_preservation_manifest,
    "/api/dual-desk-architecture": r_dual_desk_architecture,
    "/api/active-research-methods": r_active_research_methods,
    "/api/model-tournament": r_model_tournament,
    "/api/research-adapter": r_research_adapter,
    "/api/fundamentals": r_fundamentals,
    "/api/market-layers": r_market_layers,
    "/api/deep-scan": r_deep_scan,
    "/api/refresh": r_refresh,
    "/api/evidence/today": r_evidence_today,
    "/api/evidence/history": r_evidence_history,
    "/api/market-object": r_market_object,
    "/api/action-objects": r_action_objects, "/api/intelligence/action-objects": r_action_objects,
    "/api/action-object": r_action_object_symbol, "/api/intelligence/action-object": r_action_object_symbol,
    "/api/action-objects/history": r_action_objects_history,
    "/api/validation/status": r_validation_status,
    "/api/selection-fairness": r_selection_fairness,
    "/api/capital-readiness": r_capital_readiness,
    "/api/risk-authority": r_risk_authority, "/api/risk-authority/status": r_risk_authority,
    "/api/engineering-quality": r_engineering_quality,
    "/api/institutional-performance": r_institutional_performance,
    "/api/ai/governance": r_ai_governance,
    "/api/storage-architecture": r_storage_architecture,
    "/api/canonical-bars": r_canonical_bars,
    "/api/binding-mtf-contract": r_binding_mtf_contract,
    "/api/simulation-robustness": r_simulation_robustness,
    "/api/nse-feature-manifest": r_nse_feature_manifest,
    "/api/nse-data-authority": r_nse_data_authority,
    "/api/instrument-brand-assets": r_instrument_brand_assets,
    "/api/selection-platform": r_selection_platform,
    "/api/selection-research-validation": r_selection_research_validation,
    "/api/research-final-attribution": r_research_final_attribution,
    "/api/final-performance-rolling": r_final_rolling_performance,
    "/api/forward-evidence-clock": r_forward_evidence_clock,
    "/api/forward-progress": r_forward_progress,
    "/api/improvement-review": r_improvement_review,
    "/api/improvement-proposals": r_improvement_proposals,
    "/api/forward-evidence-lifecycle": r_forward_evidence_lifecycle,
    "/api/selection-walk-forward-replay": r_selection_walk_forward_replay,
    "/api/calibrated-challenger/status": r_calibrated_challenger_status,
    "/api/research-maturity": r_research_maturity,
    "/api/market-cycle-maturity": r_market_cycle_maturity,
    "/api/regime-change/status": r_regime_change_status,
    "/api/product-maturity": r_product_maturity,
    "/api/level5-forward-maturity": r_level5_forward_maturity,
    "/api/decision-surface-reconciliation": r_decision_surface_reconciliation,
    "/api/model-learning-audit": r_model_learning_audit,
    "/api/operational-evidence-integrity": r_operational_evidence_integrity,
    "/api/evidence-pipeline/status": r_evidence_pipeline_status,
    "/api/quant-edge/status": r_quant_edge_status,
    "/api/quant-edge/paper-status": r_quant_paper_status,
    "/api/positions": r_positions,
    "/api/quant-research-plane": r_quant_research_plane,
    "/api/quant-model-governance": r_quant_model_governance,
    "/api/counterfactual-learning": r_counterfactual_learning,
    "/api/winrate-controls": r_winrate_controls,
    "/api/level5-learning-loop": r_level5_learning_loop,
    "/api/factor-dedup": r_factor_dedup_status,
    "/api/cost-model": r_cost_model,
}


def match_prefix(path: str):
    """Handles the one prefix route: /api/market/index/{name}/stocks"""
    if path.startswith("/api/market/index/") and path.endswith("/stocks"):
        from reference_catalog import final_index_stocks_payload
        raw = path[len("/api/market/index/"):-len("/stocks")]

        def _handler(app, qs, q, mode, _raw=raw):
            return final_index_stocks_payload(app, unquote(_raw))
        return _handler
    return None
